name: origin_design_system
description: Origin design system.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  widgetbook: ^2.4.1
  
dev_dependencies:
  assets_gen: ^1.5.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  widgetbook_annotation: ^2.1.0
  widgetbook_generator: ^2.4.1  

flutter:
  uses-material-design: true
  assets:
    - assets/