// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'origin_design_system';

  static const String assets_origin_icon_circle_svg = 'assets/origin_icon_circle.svg';
  static const String origin_design_system$assets_origin_icon_circle_svg = 'packages/origin_design_system/assets/origin_icon_circle.svg';
}
