// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 4.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'origin_design_system';

  static const String assets_dollar_sign_svg = 'assets/dollar-sign.svg';
  static const String origin_design_system$assets_dollar_sign_svg = 'packages/origin_design_system/assets/dollar-sign.svg';

  static const String assets_lock_svg = 'assets/lock.svg';
  static const String origin_design_system$assets_lock_svg = 'packages/origin_design_system/assets/lock.svg';

  static const String assets_logo_svg = 'assets/logo.svg';
  static const String origin_design_system$assets_logo_svg = 'packages/origin_design_system/assets/logo.svg';

  static const String assets_origin_icon_circle_svg = 'assets/origin_icon_circle.svg';
  static const String origin_design_system$assets_origin_icon_circle_svg = 'packages/origin_design_system/assets/origin_icon_circle.svg';
}
